# Generated by Django 3.1.3 on 2021-08-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True, verbose_name='Полученная ссылка')),
                ('short_url', models.CharField(max_length=100, null=True, unique=True, verbose_name='Короткая ссылка')),
                ('end_time', models.TimeField(null=True, verbose_name='Дедлайн ссылки')),
            ],
        ),
    ]
